export interface ToolVideoData {
  hookProblem: string;
  character: string;
  exampleSetup: string;
  formulaPlain: string;
  exampleWalkthrough: string;
  exampleResult: string;
  exampleImplication: string;
  notableFeature: string;
  proTipMistake: string;
  proTipFix: string;
}

export const VIDEO_DATA: Record<string, ToolVideoData> = {

  'bmi-calculator': {
    hookProblem: 'figure out whether your weight is healthy for your height, without any complicated math',
    character: 'Sarah, a 32-year-old nurse',
    exampleSetup: "She's 168 cm tall and weighs 72 kg",
    formulaPlain: 'weight in kilograms divided by height in metres squared',
    exampleWalkthrough: '72 divided by 1.68 squared — which is 2.8224 — gives us 25.5',
    exampleResult: "25.5 — that puts Sarah in the Overweight category",
    exampleImplication: "she's just above the healthy range of 18.5 to 25, suggesting modest weight management could help",
    notableFeature: 'a visual BMI chart showing exactly where you land across the full spectrum',
    proTipMistake: 'entering height in centimetres without converting to metres first',
    proTipFix: 'the tool accepts both cm and feet and inches, so just select your preferred unit before entering the value',
  },

  'body-fat-calculator': {
    hookProblem: 'measure your body fat percentage without an expensive lab test or DEXA scan',
    character: 'Alex, a 35-year-old office worker',
    exampleSetup: "He's 180 cm tall, with a waist of 91 cm and neck of 38 cm",
    formulaPlain: 'waist circumference minus neck circumference plus height, all run through a logarithmic equation developed by the U.S. Navy',
    exampleWalkthrough: 'plugging those numbers into the Navy formula gives 86.01 times log of 53, minus 70.04 times log of 180, plus 36.76',
    exampleResult: "21.3% — that's the Fitness category for men",
    exampleImplication: "he's in a healthy range, though the Athletic tier starts at 14%, which is a common fitness goal",
    notableFeature: 'a full breakdown showing fat mass, lean mass, and your body fat category',
    proTipMistake: 'measuring the waist at the belly button instead of the narrowest point',
    proTipFix: 'find the narrowest part of your torso — usually 2 to 3 cm above the navel — for an accurate reading',
  },

  'ffmi-calculator': {
    hookProblem: "know whether your muscle mass is genuinely impressive or within natural limits, without relying on bodyweight alone",
    character: 'Marcus, a 28-year-old who has been lifting for three years',
    exampleSetup: "He weighs 85 kg, stands 180 cm tall, and has 15% body fat",
    formulaPlain: 'lean body mass in kilograms divided by height in metres squared, then normalised to a standard height of 1.8 metres',
    exampleWalkthrough: 'lean mass is 85 times 0.85, which is 72.25 kg. Divided by 1.8 squared gives an FFMI of 22.3',
    exampleResult: "22.3 — above average and approaching the Elite category",
    exampleImplication: 'the natural limit is generally considered around 25 to 26, so Marcus has solid progress without approaching suspicious territory',
    notableFeature: 'a category table showing average, above average, excellent, and elite thresholds with the natural ceiling clearly marked',
    proTipMistake: 'comparing FFMI scores without accounting for body fat first, which inflates the number',
    proTipFix: 'always input your most accurate body fat estimate — FFMI is calculated from lean mass, so a rough guess throws the result off',
  },

  'ideal-weight-calculator': {
    hookProblem: 'find a target weight that is realistic for your height and frame, rather than relying on a single generic number',
    character: 'Emma, a 40-year-old woman who is 165 cm tall',
    exampleSetup: "She's 165 cm and wants to know her ideal weight range",
    formulaPlain: 'the Hamwi formula starts at 45.5 kg for 152 cm and adds 2.3 kg for every additional 2.5 cm of height',
    exampleWalkthrough: '165 minus 152 is 13 cm, roughly 5.2 inches. Times 2.3 gives 11.9, plus 45.5 equals 57.4 kg',
    exampleResult: '57 to 63 kg — the average across four well-known formulas',
    exampleImplication: 'the tool shows the Hamwi, Devine, Robinson, and Miller formulas side by side, giving a range rather than a single number',
    notableFeature: 'a comparison of all four formula results alongside your current weight, so you see the full picture at once',
    proTipMistake: 'treating the result as a strict personal target',
    proTipFix: 'ideal weight formulas are guides, not goals. Your healthy weight depends on muscle mass, bone density, and body composition, not height alone',
  },

  'lean-body-mass-calculator': {
    hookProblem: 'separate your muscle and bone mass from your fat mass, so you know what you are actually working with',
    character: 'David, a 45-year-old male who is 175 cm tall and weighs 88 kg with 22% body fat',
    exampleSetup: "He's 175 cm, 88 kg, with 22% body fat",
    formulaPlain: 'the Boer formula for men is 0.407 times weight plus 0.267 times height minus 19.2',
    exampleWalkthrough: '0.407 times 88 is 35.8. Plus 0.267 times 175 which is 46.7. Minus 19.2 equals 63.3 kg',
    exampleResult: '63.3 kg lean body mass — meaning roughly 24.7 kg of fat mass',
    exampleImplication: "knowing his lean mass helps David set a protein intake target, typically 1.6 to 2.2 grams per kilogram of lean body mass per day",
    notableFeature: 'a breakdown of fat mass versus lean mass alongside your FFMI estimate',
    proTipMistake: 'confusing lean body mass with muscle mass — LBM includes organs, bones, blood, and water, not just muscle',
    proTipFix: 'think of LBM as everything that is not fat. Actual skeletal muscle is roughly 40 to 50 percent of your lean mass',
  },

  'loan-payment-calculator': {
    hookProblem: 'know exactly what your monthly payment will be before you sign a loan agreement',
    character: 'Maria, who is buying a used car for 18,000 euros',
    exampleSetup: 'She borrows 18,000 at 6.5% annual interest over 5 years',
    formulaPlain: 'the monthly payment equals the loan amount times the monthly rate, divided by one minus the quantity of one plus the monthly rate raised to the negative number of payments',
    exampleWalkthrough: 'monthly rate is 6.5% divided by 12, which is 0.00542. Applying the formula to 18,000 over 60 months gives 351.90 euros',
    exampleResult: '351.90 euros per month, totalling 21,114 euros including 3,114 in interest',
    exampleImplication: 'the interest total shows Maria pays 17% above the principal — comparing rates before signing can save thousands',
    notableFeature: 'a full amortisation breakdown showing how much of each payment goes to principal versus interest over time',
    proTipMistake: 'confusing the annual interest rate with the monthly rate',
    proTipFix: 'always enter the annual rate — the tool divides by 12 automatically. Entering the monthly rate directly would massively overstate your payments',
  },

  'compound-interest-calculator': {
    hookProblem: 'visualise exactly how your savings or investment will grow over time with compounding returns',
    character: 'James, a 30-year-old investing 5,000 euros with 200 euros added monthly',
    exampleSetup: 'He invests 5,000 initially, adds 200 per month at 7% annual return, for 20 years',
    formulaPlain: 'the future value equals the principal times one plus rate per period raised to the number of periods, plus each monthly contribution compounded forward over the remaining periods',
    exampleWalkthrough: 'at 7% compounded monthly over 240 months, the 5,000 grows to 20,489 and the monthly contributions total 104,614, for a combined 125,103',
    exampleResult: '125,103 euros — from only 53,000 invested. The compounding gains alone are 72,103 euros',
    exampleImplication: 'the gap between total invested and total value is pure compound growth — this is why starting early matters far more than the monthly contribution amount',
    notableFeature: 'a year-by-year table showing balance growth alongside a chart that makes the compounding curve immediately visible',
    proTipMistake: 'setting the compounding frequency to yearly when most savings accounts and investments compound monthly or daily',
    proTipFix: "check your account terms for the compounding frequency — monthly is the most common for savings accounts and gives a noticeably different result over long periods",
  },

  'roi-calculator': {
    hookProblem: 'compare the return on two different investments or business decisions on equal terms',
    character: 'Tom, a product manager evaluating a 12,000 euro marketing campaign that generated 18,500 in revenue',
    exampleSetup: 'Campaign cost: 12,000. Net gain: 18,500 minus 12,000, which is 6,500',
    formulaPlain: 'ROI equals net gain divided by the cost of investment, multiplied by 100 to get a percentage',
    exampleWalkthrough: '6,500 divided by 12,000 is 0.5417. Times 100 equals 54.2%',
    exampleResult: "54.2% ROI — Tom's campaign returned 1.54 euros for every euro spent",
    exampleImplication: "a positive ROI is good, but comparing it to the company's target return — often 20 to 30% — is what makes it actionable",
    notableFeature: 'the return-per-euro ratio alongside the percentage, so you can communicate it either way',
    proTipMistake: 'using total revenue as the gain instead of net profit',
    proTipFix: 'always subtract your total cost from the return to get net gain before dividing. Revenue minus costs equals the real gain — using gross revenue inflates ROI significantly',
  },

  'salary-to-hourly-calculator': {
    hookProblem: 'compare a salaried job offer to an hourly role, or figure out what you actually earn per hour',
    character: 'Lisa, who has just been offered a 52,000 euro annual salary',
    exampleSetup: '52,000 euro annual salary, standard 40-hour week, 52 weeks per year',
    formulaPlain: 'annual salary divided by the total number of hours worked per year — 40 times 52 equals 2,080 hours',
    exampleWalkthrough: '52,000 divided by 2,080 equals 25 euros per hour',
    exampleResult: '25 euros per hour, before tax',
    exampleImplication: "if Lisa is comparing this to a contracting role at 30 euros per hour, she also needs to account for vacation pay and benefits embedded in the salary",
    notableFeature: 'all pay period breakdowns at once: annual, monthly, biweekly, weekly, daily, and hourly',
    proTipMistake: 'calculating the hourly rate based on 52 weeks without subtracting paid holiday',
    proTipFix: 'for a true hourly equivalent when comparing against freelance rates, subtract paid holiday weeks — typically 4 to 6 for salaried employees — from the 52-week total',
  },

  'pay-raise-calculator': {
    hookProblem: 'quickly calculate what your new salary will be after a pay raise and see the real monthly difference',
    character: 'Ryan, earning 45,000 euros who has been offered a 7% raise',
    exampleSetup: 'Current salary: 45,000. Raise: 7%',
    formulaPlain: 'new salary equals current salary times one plus the raise percentage divided by 100',
    exampleWalkthrough: '45,000 times 1.07 equals 48,150 euros per year',
    exampleResult: '48,150 euros — a 3,150 euro increase per year, or 262.50 per month',
    exampleImplication: 'the monthly figure is what hits the bank account — comparing it against current living costs tells you whether the raise keeps pace with inflation',
    notableFeature: 'the increase broken down at every pay period: annual, monthly, biweekly, weekly, and daily',
    proTipMistake: 'comparing the raise percentage against inflation without adjusting — a 7% raise in a year with 6% inflation is only a 1% real gain',
    proTipFix: 'subtract the current inflation rate from your raise percentage to find your real purchasing power increase',
  },

  'annual-income-calculator': {
    hookProblem: 'figure out your total annual income when you get paid weekly, biweekly, or on any irregular schedule',
    character: 'Sophie, a freelancer who earns 1,850 euros biweekly',
    exampleSetup: '1,850 euros paid every two weeks',
    formulaPlain: 'multiply the pay amount by the number of pay periods in a year — biweekly means 26 periods, not 24',
    exampleWalkthrough: '1,850 times 26 equals 48,100 euros',
    exampleResult: '48,100 euros annually',
    exampleImplication: 'this matters most when comparing job offers with different pay schedules — a 2,000 monthly salary is 24,000 annually, significantly less than 48,100',
    notableFeature: 'all pay period equivalents displayed together: annual, monthly, biweekly, weekly, and hourly',
    proTipMistake: 'multiplying a biweekly pay by 24 instead of 26',
    proTipFix: 'biweekly means every two weeks. 52 weeks divided by 2 gives 26 pay periods — not 24 months. Multiplying by 24 understates annual income by two full paycheques',
  },

  'break-even-calculator': {
    hookProblem: 'know exactly how many units you need to sell before your business starts making a profit',
    character: 'Nina, who makes handmade candles and wants to know if her pricing makes sense',
    exampleSetup: 'Fixed costs: 800 euros per month. Variable cost per candle: 4 euros. Selling price: 14 euros',
    formulaPlain: 'break-even units equals fixed costs divided by price per unit minus variable cost per unit — this difference is the contribution margin',
    exampleWalkthrough: '800 divided by 14 minus 4 equals 800 divided by 10, which is 80 units',
    exampleResult: '80 candles per month to break even',
    exampleImplication: 'if Nina currently sells 60 candles, she is losing 200 euros a month. Knowing this tells her whether to raise prices, cut costs, or grow sales',
    notableFeature: 'a margin of safety calculation showing how far sales can drop before hitting a loss',
    proTipMistake: "forgetting to include their own time as a variable cost",
    proTipFix: 'if you work in the business yourself, assign an hourly rate and include it as a variable cost per unit. Without this, your break-even point is misleadingly low',
  },

  'contribution-margin-calculator': {
    hookProblem: 'see how much of each sale actually contributes to covering your fixed costs and eventually generating profit',
    character: 'Oliver, who runs a software subscription at 49 euros per month with 8 euros in infrastructure costs per user',
    exampleSetup: 'Price: 49 euros. Variable cost per user: 8 euros',
    formulaPlain: 'contribution margin equals selling price minus variable costs. The margin ratio is that result divided by price, times 100',
    exampleWalkthrough: '49 minus 8 is 41 euros contribution margin. Divided by 49 gives 83.7%',
    exampleResult: '41 euros contribution margin — an 83.7% contribution margin ratio',
    exampleImplication: 'an 83.7% ratio is excellent for SaaS, meaning each new user generates 41 euros toward fixed costs and eventually profit',
    notableFeature: 'the contribution margin ratio alongside the raw amount — the ratio is what you use to compare across products with different prices',
    proTipMistake: 'including fixed cost allocations in the variable cost field, which distorts the contribution margin',
    proTipFix: 'variable costs only include what changes with each unit sold: hosting per user, payment processing, materials. Rent and salaries go into fixed costs',
  },

  'ebit-calculator': {
    hookProblem: "evaluate a company's core operating profit without the noise of its debt structure or tax situation",
    character: 'Carla, a finance student analysing a company with 500,000 in revenue',
    exampleSetup: 'Revenue: 500,000. COGS: 200,000. Operating expenses: 120,000',
    formulaPlain: 'EBIT equals revenue minus cost of goods sold minus operating expenses — it is simply operating profit',
    exampleWalkthrough: '500,000 minus 200,000 is 300,000 gross profit. Minus 120,000 operating expenses equals 180,000 EBIT',
    exampleResult: '180,000 EBIT — a 36% EBIT margin',
    exampleImplication: 'the margin tells Carla that for every euro of revenue, the company keeps 36 cents before interest and tax — above the median for most industries',
    notableFeature: 'EBIT margin percentage calculated alongside the raw figure',
    proTipMistake: 'confusing EBIT with gross profit — EBIT deducts all operating expenses including SG&A and R&D, not just cost of goods',
    proTipFix: 'if you have a net income figure and want EBIT, add back interest expense and income tax expense to work backwards',
  },

  'ebitda-calculator': {
    hookProblem: 'compare two businesses on their operational cash generation, stripping out financing and accounting differences',
    character: 'Ben, an analyst comparing two acquisition targets',
    exampleSetup: 'Company A: EBIT 200,000. Depreciation: 30,000. Amortisation: 10,000',
    formulaPlain: 'EBITDA equals EBIT plus depreciation plus amortisation',
    exampleWalkthrough: '200,000 plus 30,000 plus 10,000 equals 240,000',
    exampleResult: '240,000 EBITDA',
    exampleImplication: 'EBITDA removes non-cash charges, making it easier to compare businesses regardless of how they finance assets. It is the most common multiple used in M&A valuation',
    notableFeature: 'EBITDA margin shown alongside the absolute figure for quick benchmarking',
    proTipMistake: 'using EBITDA as a direct proxy for cash flow',
    proTipFix: "EBITDA ignores capital expenditure, which can be substantial for asset-heavy businesses. Pair it with capex data to get a cleaner picture of actual cash generation",
  },

  'ebitda-margin-calculator': {
    hookProblem: 'benchmark how efficiently a company converts revenue to operating profit compared to its peers',
    character: 'Priya, comparing two SaaS companies before investing',
    exampleSetup: 'Company A: EBITDA 4.2M on revenue of 18M',
    formulaPlain: 'EBITDA margin equals EBITDA divided by total revenue, multiplied by 100',
    exampleWalkthrough: '4.2 divided by 18 times 100 equals 23.3%',
    exampleResult: '23.3% EBITDA margin',
    exampleImplication: "for SaaS companies, a healthy margin is often considered 20% or above. Priya can now compare Company A's 23.3% directly against Company B",
    notableFeature: 'industry benchmark context on the result page so you can see immediately whether the margin is strong or weak for the sector',
    proTipMistake: 'comparing EBITDA margins across very different industries',
    proTipFix: 'a 15% margin is excellent for a grocery chain but weak for a software company. Always compare margins within the same industry vertical',
  },

  'ebt-calculator': {
    hookProblem: "isolate a company's profitability before tax effects, which vary by country and tax strategy",
    character: 'Stefan, comparing the pre-tax earnings of two subsidiaries operating in different countries',
    exampleSetup: 'EBIT: 180,000. Interest expense: 15,000. Interest income: 2,000',
    formulaPlain: 'EBT equals EBIT minus net interest expense, where net interest is interest expense minus interest income',
    exampleWalkthrough: '180,000 minus 15,000 plus 2,000 equals 167,000',
    exampleResult: '167,000 EBT',
    exampleImplication: 'comparing EBT across subsidiaries removes the distortion of different national tax rates, giving a cleaner view of operational performance',
    notableFeature: 'a step-by-step breakdown from revenue to EBT showing exactly where each deduction sits',
    proTipMistake: 'entering interest expense as a negative number',
    proTipFix: 'enter all figures as positive amounts. The calculator handles sign conventions internally — interest expense is subtracted and interest income is added automatically',
  },

  'enterprise-value-calculator': {
    hookProblem: 'calculate what a company is actually worth as an acquisition target, accounting for its debt and cash position',
    character: 'Hana, a junior analyst valuing a mid-size tech company',
    exampleSetup: 'Market cap: 80M. Total debt: 20M. Cash: 5M. Minority interest: 2M',
    formulaPlain: 'enterprise value equals market capitalisation plus total debt plus minority interest, minus cash and cash equivalents',
    exampleWalkthrough: '80M plus 20M plus 2M minus 5M equals 97M enterprise value',
    exampleResult: '97M enterprise value',
    exampleImplication: 'the 97M figure is what a buyer would effectively pay to own the entire business including its debt obligations — a more accurate M&A price than market cap alone',
    notableFeature: 'EV/EBITDA and EV/Revenue multiples calculated automatically when you add revenue and EBITDA figures',
    proTipMistake: 'using book value of debt instead of market value',
    proTipFix: 'for publicly traded debt, use the current trading price. For private companies where market value is unavailable, book value is an acceptable approximation',
  },

  'free-cash-flow-calculator': {
    hookProblem: 'find out how much real cash a business generates after maintaining and expanding its asset base',
    character: "Liam, reviewing a company's annual report before investing",
    exampleSetup: 'Operating cash flow: 85,000. Capital expenditure: 22,000',
    formulaPlain: 'free cash flow equals operating cash flow minus capital expenditure',
    exampleWalkthrough: '85,000 minus 22,000 equals 63,000',
    exampleResult: '63,000 free cash flow',
    exampleImplication: 'FCF is the cash available for dividends, debt repayment, share buybacks, or reinvestment. Positive and growing FCF is generally a stronger signal than earnings alone',
    notableFeature: 'FCF yield calculated when you input market cap — this lets you compare FCF directly against the current valuation',
    proTipMistake: 'using net income instead of operating cash flow',
    proTipFix: 'net income includes non-cash items like depreciation that do not affect actual cash. Always use the operating cash flow line from the cash flow statement',
  },

  'google-adsense-calculator': {
    hookProblem: 'estimate your monthly AdSense revenue before launching a site, so you know exactly what traffic you need',
    character: 'Julia, who is launching a recipe blog and wants to know when it becomes financially viable',
    exampleSetup: 'Monthly pageviews: 50,000. Page RPM: 3 euros',
    formulaPlain: 'monthly revenue equals monthly pageviews divided by 1,000, multiplied by your RPM',
    exampleWalkthrough: '50,000 divided by 1,000 is 50. Times 3 euros RPM equals 150 euros per month',
    exampleResult: '150 euros per month at 50,000 pageviews',
    exampleImplication: 'to hit 1,000 euros per month with a 3 euro RPM, Julia needs 333,000 monthly pageviews — a realistic 12 to 18 month goal for a focused niche site',
    notableFeature: 'a revenue table showing earnings at different traffic milestones, so you can plan your growth targets backward from an income goal',
    proTipMistake: 'using a generic 2 to 3 euro RPM across all niches',
    proTipFix: 'finance and insurance niches can command 15 to 40 euros RPM while entertainment sits closer to 1 euro. Research benchmarks specific to your topic before using the calculator',
  },

  'gross-profit-margin-calculator': {
    hookProblem: 'see how much of your revenue remains after paying for the goods or services you sell',
    character: 'Daniel, who runs an e-commerce store with 80,000 in revenue and 55,000 in cost of goods',
    exampleSetup: 'Revenue: 80,000. COGS: 55,000',
    formulaPlain: 'gross profit margin equals revenue minus cost of goods sold, divided by revenue, multiplied by 100',
    exampleWalkthrough: '80,000 minus 55,000 is 25,000 gross profit. Divided by 80,000 times 100 equals 31.25%',
    exampleResult: '31.25% gross margin',
    exampleImplication: "e-commerce typically targets 30 to 50% gross margin. Daniel's 31.25% is at the lower end, which may limit his ability to cover operating costs and still profit",
    notableFeature: 'gross profit in euros alongside the margin percentage — the raw number tells you what you have available to cover all other costs',
    proTipMistake: 'including operating expenses like rent and wages in the COGS field',
    proTipFix: 'COGS covers only direct production or purchase costs: materials, manufacturing, and direct labour. Marketing, admin, and rent are operating expenses and go elsewhere',
  },

  'net-profit-margin-calculator': {
    hookProblem: 'find out what percentage of your revenue actually becomes profit after every single cost is paid',
    character: 'Isabelle, who runs a small catering company with 95,000 in annual revenue',
    exampleSetup: 'Revenue: 95,000. Total costs including COGS, wages, rent, and taxes: 81,000',
    formulaPlain: 'net profit margin equals net profit divided by revenue times 100, where net profit is revenue minus all expenses',
    exampleWalkthrough: '95,000 minus 81,000 is 14,000 net profit. Divided by 95,000 times 100 equals 14.7%',
    exampleResult: '14.7% net profit margin',
    exampleImplication: 'the average for small service businesses is 7 to 10%, so 14.7% is healthy — Isabelle keeps more of every euro than most in her sector',
    notableFeature: 'gross margin shown alongside net margin — the gap between them reveals your total operating cost burden',
    proTipMistake: 'confusing profit margin with markup — a 30% markup does not mean a 30% margin',
    proTipFix: 'markup is cost-based: 30% on a 10 euro item means selling for 13 euros. Margin is revenue-based: 3 euros profit on 13 euros revenue is a 23% margin, not 30%',
  },

  'operating-profit-margin-calculator': {
    hookProblem: 'measure how efficiently a business earns profit from its core operations, separate from interest and taxes',
    character: 'Kai, a startup founder reviewing his P&L before a board meeting',
    exampleSetup: 'Revenue: 200,000. COGS: 80,000. Operating expenses: 60,000',
    formulaPlain: 'operating profit equals revenue minus COGS minus operating expenses. Operating margin is that divided by revenue times 100',
    exampleWalkthrough: '200,000 minus 80,000 minus 60,000 equals 60,000 operating profit. Divided by 200,000 times 100 equals 30%',
    exampleResult: '30% operating profit margin',
    exampleImplication: 'a 30% operating margin is strong for most industries, but what matters most is whether it improves quarter over quarter as revenue scales',
    notableFeature: 'operating margin displayed alongside gross and net margins to show the full profitability waterfall in one view',
    proTipMistake: 'including interest expense or tax in the operating expense figure',
    proTipFix: 'operating profit is calculated before interest and tax. If working from a P&L, use total operating expenses that stop before the interest line',
  },

  'overtime-calculator': {
    hookProblem: 'calculate your exact pay for overtime hours, whether your rate is time-and-a-half, double time, or something else',
    character: 'Marco, who earns 18 euros per hour and worked 48 hours last week',
    exampleSetup: 'Regular rate: 18 euros per hour. Hours worked: 48. Overtime after: 40 hours. Overtime multiplier: 1.5x',
    formulaPlain: 'regular pay equals regular rate times standard hours. Overtime pay equals regular rate times multiplier times overtime hours',
    exampleWalkthrough: 'regular pay: 18 times 40 equals 720 euros. Overtime: 18 times 1.5 times 8 equals 216 euros. Total: 936 euros',
    exampleResult: '936 euros for the week — 216 euros of that is overtime pay',
    exampleImplication: '8 overtime hours adds 30% to the weekly pay. Over a month of consistent overtime, that is a meaningful income increase',
    notableFeature: 'regular weekly total and overtime premium shown separately, so you can see exactly what the extra hours are worth',
    proTipMistake: 'assuming overtime starts after 8 hours in a single day',
    proTipFix: 'in most countries, overtime is calculated weekly after 40 hours, not daily. Check your employment contract or local labour law — some industries use daily thresholds',
  },

  'pe-ratio-calculator': {
    hookProblem: 'quickly assess whether a stock is expensive or cheap relative to its earnings',
    character: 'Anya, considering buying shares in a tech company trading at 45 euros per share',
    exampleSetup: 'Share price: 45 euros. Earnings per share: 3 euros',
    formulaPlain: 'P/E ratio equals the current share price divided by earnings per share',
    exampleWalkthrough: '45 divided by 3 equals a P/E ratio of 15',
    exampleResult: 'P/E of 15 — the stock is priced at 15 times its annual earnings',
    exampleImplication: 'the S&P 500 long-term average P/E is around 16, so at 15 this company is roughly fairly valued. Comparing against the sector average gives far more context',
    notableFeature: 'earnings yield calculated alongside P/E — yield is 1 divided by P/E as a percentage, making it easy to compare against bond yields or alternative investments',
    proTipMistake: 'relying only on trailing P/E without considering forward P/E, which accounts for expected earnings growth',
    proTipFix: 'a high trailing P/E may be justified if earnings are expected to grow rapidly. Compare P/E against the growth rate using the PEG ratio for a more complete picture',
  },

  'roe-calculator': {
    hookProblem: "measure how effectively a company uses its shareholders' equity to generate profit",
    character: 'Fatima, evaluating two competing investment options with similar revenue',
    exampleSetup: 'Net income: 45,000. Shareholder equity: 300,000',
    formulaPlain: 'return on equity equals net income divided by average shareholder equity, multiplied by 100',
    exampleWalkthrough: '45,000 divided by 300,000 times 100 equals 15%',
    exampleResult: '15% ROE',
    exampleImplication: 'Warren Buffett commonly looks for companies with ROE above 15% sustained over time — this company sits right at that threshold',
    notableFeature: 'a DuPont decomposition breaking ROE into profit margin, asset turnover, and leverage, revealing which driver is creating the return',
    proTipMistake: 'treating high ROE as automatically positive when it is driven by high debt rather than genuine profitability',
    proTipFix: 'always check the debt-to-equity ratio alongside ROE. A company with 15% ROE and low debt is far more attractive than one with 20% ROE funded by heavy borrowing',
  },

  'working-capital-calculator': {
    hookProblem: 'assess whether a business has enough short-term assets to cover its short-term obligations',
    character: "Hugo, a CFO reviewing his company's quarterly liquidity position",
    exampleSetup: 'Current assets: 250,000. Current liabilities: 180,000',
    formulaPlain: 'working capital equals current assets minus current liabilities. The current ratio is current assets divided by current liabilities',
    exampleWalkthrough: '250,000 minus 180,000 equals 70,000 working capital. 250,000 divided by 180,000 equals a current ratio of 1.39',
    exampleResult: '70,000 working capital. Current ratio: 1.39',
    exampleImplication: "a current ratio above 1.0 means Hugo's company can cover all short-term debts. Below 1.5 is often watched closely by creditors as a potential stress signal",
    notableFeature: 'current ratio alongside the raw working capital figure — lenders focus on the ratio while the raw number tells you the actual buffer in currency',
    proTipMistake: 'including long-term assets like property or long-term liabilities like bonds in the working capital calculation',
    proTipFix: 'working capital only uses current assets and current liabilities — items expected to be converted or settled within 12 months. Check balance sheet labels carefully',
  },

  'case-converter': {
    hookProblem: 'reformat text to a specific capitalisation style — title case, camelCase, slug format, or any other — in one click',
    character: 'Wei, a developer converting 30 database column headers from sentence case to snake_case',
    exampleSetup: "Input: 'Total Monthly Revenue by Region'",
    formulaPlain: 'each case style applies a different rule: snake_case replaces spaces with underscores and lowercases everything, camelCase capitalises each word except the first, and title case capitalises the first letter of each significant word',
    exampleWalkthrough: "'Total Monthly Revenue by Region' becomes total_monthly_revenue_by_region in snake_case, totalMonthlyRevenueByRegion in camelCase, and Total Monthly Revenue by Region in title case",
    exampleResult: 'instant conversion across all 8 case formats simultaneously',
    exampleImplication: 'manually reformatting 30 column headers takes minutes and introduces typos. This takes two seconds and shows all formats at once',
    notableFeature: 'all case variants shown simultaneously so you can pick the right one without running the tool multiple times',
    proTipMistake: 'using title case for code class names — in programming, title case for classes means PascalCase, not standard title case',
    proTipFix: 'use PascalCase for class names, camelCase for variables and functions, and snake_case for database columns and Python variables. The tool provides all three separately',
  },

  'currency-converter': {
    hookProblem: 'convert between any two currencies at the current mid-market rate before booking travel or making an international payment',
    character: 'Anna, planning a trip to Japan from Denmark and wanting to know how many yen her 10,000 kroner will buy',
    exampleSetup: '10,000 DKK to JPY at the current mid-market rate',
    formulaPlain: 'the converted amount equals the original amount multiplied by the current exchange rate between the two currencies',
    exampleWalkthrough: 'if the current DKK to JPY rate is 20.5, then 10,000 times 20.5 gives 205,000 yen',
    exampleResult: 'approximately 205,000 JPY — though this moves daily as exchange rates shift',
    exampleImplication: 'mid-market rates are the fairest benchmark. Banks and exchange services typically mark up 2 to 5% from this rate, so knowing it tells you what a fair conversion looks like',
    notableFeature: 'a reference table showing common round amounts in both currencies, so you can quickly check what various purchase amounts cost in your home currency',
    proTipMistake: 'using the rate your bank offers and assuming it is the real exchange rate',
    proTipFix: 'the mid-market rate is the real rate shown on Google or Reuters. Your bank adds a margin on top. Use mid-market as your benchmark and expect to pay 1 to 5% above it',
  },

  'height-converter': {
    hookProblem: 'convert your height between centimetres and feet and inches without doing the maths in your head',
    character: 'Max, born in Germany and filling out a US medical form that requires feet and inches',
    exampleSetup: '180 cm to feet and inches',
    formulaPlain: 'divide centimetres by 30.48 to get total feet as a decimal, then multiply the decimal part by 12 to get the remaining inches',
    exampleWalkthrough: '180 divided by 30.48 equals 5.906 feet. The 0.906 decimal times 12 equals 10.87 inches. So 180 cm is 5 feet 10.9 inches',
    exampleResult: "5 feet 10.9 inches — commonly written as 5'11\"",
    exampleImplication: "this is a common conversion for anyone moving between metric and imperial countries. Knowing it means 180 cm is just under 6 feet, not exactly 6 feet",
    notableFeature: 'both the decimal feet result and the split feet-and-inches result, so you can use whichever format the form or situation requires',
    proTipMistake: "rounding 180 cm to exactly 6 feet — it is actually 5 feet 10.9 inches",
    proTipFix: '1 foot equals 30.48 cm exactly, not 30 cm. Using 30 cm introduces a cumulative error that grows the taller the person',
  },

  'image-to-text': {
    hookProblem: 'extract text from a photo, scanned document, or screenshot without retyping it manually',
    character: 'Zoe, who needs to copy a data table from a scanned PDF into a spreadsheet',
    exampleSetup: 'A scanned PDF page containing a multi-column data table',
    formulaPlain: 'optical character recognition analyses pixel patterns in the image to identify characters, then assembles them into readable text while preserving the original layout where possible',
    exampleWalkthrough: 'Zoe uploads the scanned page. The OCR engine identifies each character and its position, and returns the full text output in seconds',
    exampleResult: 'the complete text content of the page, ready to copy directly into a spreadsheet',
    exampleImplication: 'retyping a dense data table manually takes 15 to 30 minutes and introduces errors. OCR takes 5 seconds and can be reviewed and cleaned in another 2 minutes',
    notableFeature: 'support for both images and PDFs, plus the ability to paste screenshots directly without saving a file first',
    proTipMistake: 'expecting perfect output from low-resolution or handwritten scans',
    proTipFix: 'for best results, use scans at 300 DPI or higher with the image straight and well-lit. Machine-printed text at good resolution achieves 98% or higher accuracy',
  },

  'length-converter': {
    hookProblem: 'convert between metric and imperial length units — metres, feet, inches, kilometres, miles — without memorising conversion factors',
    character: 'Peter, a runner who tracks workouts in kilometres but needs to report a race distance in miles',
    exampleSetup: '10 kilometres to miles',
    formulaPlain: 'multiply kilometres by 0.621371 to get miles',
    exampleWalkthrough: '10 times 0.621371 equals 6.21 miles',
    exampleResult: '6.21 miles — a 10K is just over 6 miles',
    exampleImplication: 'knowing this conversion also means every 5K is roughly 3.1 miles, and a marathon is 26.2 miles or 42.2 kilometres',
    notableFeature: 'all common length units shown in one view: millimetres, centimetres, metres, kilometres, inches, feet, yards, and miles',
    proTipMistake: 'using 1.6 km per mile as a rule of thumb',
    proTipFix: 'the exact conversion is 1 mile equals 1.60934 km. Using 1.6 introduces a 0.6% error — fine for casual estimates, but meaningful for engineering or race planning',
  },

  'speed-converter': {
    hookProblem: 'convert between mph, km/h, knots, and metres per second — whether driving, sailing, or working through a physics problem',
    character: 'Nadia, a pilot converting cruise speed from knots to km/h for a flight planning document',
    exampleSetup: '250 knots to km/h',
    formulaPlain: 'multiply knots by 1.852 to get km/h',
    exampleWalkthrough: '250 times 1.852 equals 463 km/h',
    exampleResult: '463 km/h — a typical cruise speed for a commercial aircraft',
    exampleImplication: 'pilots use knots because nautical miles align with degrees of latitude, making navigation calculations cleaner. Knowing the km/h equivalent helps when communicating with ground staff',
    notableFeature: 'all five speed units at once: km/h, mph, knots, m/s, and feet per second',
    proTipMistake: 'confusing knots with nautical miles per hour — they are the same thing',
    proTipFix: 'one knot equals one nautical mile per hour, and a nautical mile is 1,852 metres. This is precisely why the conversion factor from knots to km/h is 1.852',
  },

  'temperature-converter': {
    hookProblem: 'convert temperatures between Celsius, Fahrenheit, and Kelvin without memorising the formulas',
    character: 'Rosa, a Danish student studying in the US who sees a forecast of 95 degrees Fahrenheit',
    exampleSetup: '95 degrees Fahrenheit to Celsius',
    formulaPlain: 'subtract 32 from the Fahrenheit value, then multiply by 5 divided by 9',
    exampleWalkthrough: '95 minus 32 is 63. Times 5 divided by 9 equals 35 degrees Celsius',
    exampleResult: '35 degrees Celsius — a very hot summer day',
    exampleImplication: '35 degrees Celsius is near the upper limit for safe outdoor physical activity, which warrants sunscreen, shade, and regular hydration',
    notableFeature: 'all three scales at once — Celsius, Fahrenheit, and Kelvin — with the result shown on a scale so you can see where the temperature sits in context',
    proTipMistake: "using the shortcut of halving and adding 30 for quick estimates — this works but can be off by up to 2 degrees at extreme temperatures",
    proTipFix: 'for rough estimates, dividing Fahrenheit by 2 and subtracting 15 gives a fast answer. For accuracy in cooking, medicine, or science, use the exact formula or just use the tool',
  },

  'weight-converter': {
    hookProblem: 'convert between kilograms, pounds, stone, and ounces without reaching for a separate calculator',
    character: 'Chris, a British expat in Canada checking a recipe that lists weights in grams',
    exampleSetup: '500 grams to pounds',
    formulaPlain: 'multiply grams by 0.00220462 to get pounds, or equivalently divide by 453.592',
    exampleWalkthrough: '500 times 0.00220462 equals 1.10 pounds',
    exampleResult: '1.10 pounds — roughly 1 pound and 1.6 ounces',
    exampleImplication: 'for cooking, a handy shortcut is that 450 grams is almost exactly 1 pound, so 500 grams is just a little over',
    notableFeature: 'all weight units at once: grams, kilograms, ounces, pounds, and stone — plus metric tonnes and US short tons for larger weights',
    proTipMistake: 'confusing fluid ounces with weight ounces',
    proTipFix: 'fluid ounces measure volume, not mass — they are completely different units. Use this tool for weight ounces. For volume conversions, use a dedicated volume converter',
  },

  'percentage-calculator': {
    hookProblem: 'calculate a percentage, percentage change, or percentage difference without second-guessing which formula to use',
    character: 'Leo, a sales manager reporting quarter-over-quarter growth from 85,000 to 102,000 in revenue',
    exampleSetup: 'Old value: 85,000. New value: 102,000',
    formulaPlain: 'percentage change equals new value minus old value, divided by the old value, multiplied by 100',
    exampleWalkthrough: '102,000 minus 85,000 is 17,000. Divided by 85,000 times 100 equals 20%',
    exampleResult: '20% growth quarter over quarter',
    exampleImplication: 'Leo can report a clear 20% increase. Reporting 17,000 in absolute terms gives less context than the relative 20%',
    notableFeature: 'three calculators in one: what is X percent of Y, X is what percent of Y, and percentage change between two values',
    proTipMistake: 'confusing percentage change with percentage points — going from 10% to 15% is a 5 percentage point increase, but a 50% relative change',
    proTipFix: 'use percentage change when comparing relative growth between two values. Use percentage points only when both values are already percentages themselves',
  },

  'fraction-calculator': {
    hookProblem: 'add, subtract, multiply, or divide fractions and get a simplified result without doing it by hand',
    character: "Mia, a parent helping her 10-year-old with homework on adding three-quarters plus two-thirds",
    exampleSetup: '3/4 + 2/3',
    formulaPlain: 'to add fractions, find the lowest common denominator, convert both fractions to that denominator, then add the numerators',
    exampleWalkthrough: 'the lowest common denominator of 4 and 3 is 12. Three-quarters becomes 9 over 12. Two-thirds becomes 8 over 12. Nine plus eight is 17, giving 17/12',
    exampleResult: '17/12 — or 1 and 5/12 as a mixed number',
    exampleImplication: 'seeing the step-by-step working lets Mia explain the process to her child, not just hand over the answer',
    notableFeature: 'results in three formats: improper fraction, mixed number, and decimal — so you can use whichever the problem or situation calls for',
    proTipMistake: 'adding fractions by adding the numerators and denominators separately — 1/2 plus 1/3 is not 2/5',
    proTipFix: 'the denominator stays fixed once you find a common one. Only numerators are added after converting both fractions to the same denominator',
  },

  'ratio-calculator': {
    hookProblem: 'simplify a ratio, find an equivalent ratio, or solve for a missing value in a proportion',
    character: 'Arjun, a chef scaling a recipe from 4 portions to 18',
    exampleSetup: 'Original: 3 parts flour to 2 parts sugar for 4 portions. Target: 18 portions',
    formulaPlain: 'multiply each part of the ratio by the scaling factor, which is the target quantity divided by the original quantity',
    exampleWalkthrough: 'scaling factor is 18 divided by 4, which is 4.5. Three parts flour times 4.5 is 13.5. Two parts sugar times 4.5 is 9',
    exampleResult: '13.5 parts flour to 9 parts sugar for 18 portions',
    exampleImplication: 'Arjun can now scale every ingredient in the recipe by the same 4.5 factor, maintaining exact proportions across all components',
    notableFeature: 'simplified ratio output alongside scaled values — you always see both the proportion and the actual amounts',
    proTipMistake: 'simplifying a ratio by adding to or subtracting from each part instead of dividing by the greatest common factor',
    proTipFix: 'to simplify 12:8, find the GCF of 12 and 8, which is 4. Divide both by 4 to get 3:2. Only multiply or divide — never add or subtract from both parts',
  },

  'diff-checker': {
    hookProblem: 'find every difference between two versions of a text, document, or code file without reading through it line by line',
    character: 'Jake, a developer confirming which lines changed between two versions of a configuration file',
    exampleSetup: 'Original config file pasted on the left. Updated version pasted on the right',
    formulaPlain: 'the LCS algorithm — Longest Common Subsequence — identifies the longest sequence of lines that appear in both files in the same order. Lines outside this sequence are classified as added or removed',
    exampleWalkthrough: 'Jake pastes his original config on the left and the updated version on the right. The tool highlights removed lines in red and added lines in green, with line numbers for reference',
    exampleResult: 'a colour-coded diff showing exactly which lines were added, removed, or unchanged',
    exampleImplication: 'instead of reading 200 lines to find 3 changes, Jake sees them highlighted immediately. The side-by-side view keeps matching lines at equal height so nothing drifts out of alignment',
    notableFeature: 'a scroll indicator strip on the right side showing where all changes are distributed — click any mark to jump directly to that change',
    proTipMistake: 'comparing files with different line endings — Windows CRLF versus Unix LF — and seeing every single line flagged as changed',
    proTipFix: "if all lines show as changed but the content looks identical, the files likely use different line endings. Paste through a plain text editor first to normalise them, or switch to the Unified view to spot the hidden characters. And this same tool works for code, CSS, JavaScript, Python, HTML, and more — just pick the right variant from the compare menu.",
  },

};
